
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Apr 09 16:57:31 CST 2008
//----------------------------------------------------

package edu.ustc.cs.compile.parser.expr;

/** CUP generated class containing symbol constants. */
public class ExprSymbol {
  /* terminals */
  public static final int MINUS = 4;
  public static final int MULT = 5;
  public static final int EOF = 0;
  public static final int PLUS = 3;
  public static final int EQ = 7;
  public static final int DIV = 6;
  public static final int error = 1;
  public static final int RPAREN = 9;
  public static final int SEMICOLON = 2;
  public static final int IDENTIFIER = 11;
  public static final int LPAREN = 8;
  public static final int INTEGER_LITERAL = 10;
}

