/* Generated By:JavaCC: Do not edit this line. ExprEParserConstants.java */
package  edu.ustc.cs.compile.parser.jjexpr;

public interface ExprEParserConstants {

  int EOF = 0;
  int IDENTIFIER = 5;
  int INTEGER_LITERAL = 6;
  int LPAREN = 7;
  int RPAREN = 8;
  int SEMICOLON = 9;
  int PLUS = 10;
  int MINUS = 11;
  int MULT = 12;
  int DIV = 13;
  int EQ = 14;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<IDENTIFIER>",
    "<INTEGER_LITERAL>",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
  };

}
